
---
services:
  ocis:
    depends_on:
      mdpresentation-viewer:
        condition: service_completed_successfully

  mdpresentation-viewer:
    image: jankaritech/mdpresentation-viewer:2.0.0
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /app/* /apps"]
