services:
  ocis:
    image: owncloud/ocis-rolling:${OCIS_IMAGE_TAG:-latest}
    entrypoint: /bin/sh
    command: ['-c', 'ocis init || true && ocis server']
    ports:
      - 9200:9200
    environment:
      # OCIS
      OCIS_URL: https://localhost:9200
      OCIS_INSECURE: true
      OCIS_LOG_LEVEL: error
      # WEB
      WEB_ASSET_APPS_PATH: /web/apps
      # IDM
      IDM_CREATE_DEMO_USERS: true
      IDM_ADMIN_PASSWORD: admin
      # PROXY
      PROXY_ENABLE_BASIC_AUTH: true
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yml
    volumes:
      - ./dist:/web/apps:ro
      - ./dev/config/csp.yml:/etc/ocis/csp.yml
