
---
services:
  ocis:
    depends_on:
      md-viewer:
        condition: service_completed_successfully

  md-viewer:
    image: jankaritech/md-presentation-viewer:2.0.0
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /app/* /apps"]
