name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: [ "bug" ]
projects: [ "JankariTech/48" ]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched for an existing issue
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Steps To Reproduce
      placeholder: |
        Steps to reproduce the behavior.
        1.
        2.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Examples, Code Samples, or Screenshots
      placeholder: |
        Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      value: |
        - **OS**: Ubuntu 22.04
        - **Node**: 18.17.1
        - **pnpm**: 8.15.1
        - **ownCloud Web**: ownCloud Web UI 8.0.0
        - **oCIS**: Infinite Scale 5.0.0
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
