name: lint-build-e2e

on:
  push:
    branches:
      - main
  pull_request:

env:
  OCIS_URL: https://localhost:9200

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pnpm-install
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - name: generate-ssl-certs
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout ${{ github.workspace }}/tests/e2e/ci/nginx/nginx-ssl.key \
            -out ${{ github.workspace }}/tests/e2e/ci/nginx/nginx-ssl.crt \
            -subj "/CN=localhost"

      - name: extension-server
        run: |
          docker run --rm -d \
            -p 8443:443 \
            -v ${{ github.workspace }}/tests/e2e/ci/nginx:/etc/nginx/conf.d \
            -v ${{ github.workspace }}/dist:/usr/share/nginx/html \
            nginx:1.25.3

      - name: ocis-server
        run: |
          docker run --rm -d \
            -p 9200:9200 \
            -e OCIS_URL=$OCIS_URL \
            -e OCIS_INSECURE=true \
            -e OCIS_LOG_LEVEL=error \
            -e WEB_UI_CONFIG_FILE=/web/config.json \
            -e IDM_ADMIN_PASSWORD=admin \
            -e PROXY_ENABLE_BASIC_AUTH=true \
            -v ${{ github.workspace }}/tests/e2e/ci/web.config.json:/web/config.json:ro \
            --entrypoint sh \
            owncloud/ocis:5.0.0 \
            -c 'ocis init || true && ocis server'

      - name: host-ip
        id: host_ip
        run: echo "host_ip=$(hostname -I | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: wait-services
        run: |
          docker run --rm \
            --add-host dockerhost:${{ steps.host_ip.outputs.host_ip }} \
            owncloudci/wait-for \
            -it dockerhost:8443,dockerhost:9200 -t 10

      - name: install-chromium
        run: npx playwright install chromium

      - name: e2e
        run: pnpm test:e2e tests/e2e/features/**/*.feature
        env:
          HEADLESS: true
