name: release

on:
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish-artifacts:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: download-dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: create-zip
        run: echo mdpresentation-${{ github.ref_name }}.zip
        # mkdir dist/release && (cd dist && zip -r - .) >dist/release/mdpresentation-${{ github.ref_name }}.zip

      # - name: publish-artifacts
      #   uses: fnkr/github-action-ghr@v1
      #   env:
      #     GHR_PATH: dist/release/
      #     GHR_REPLACE: true
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
